### ISSUE TITLE
Variables in scss files

### ISSUE THREAD

**Issue by penguoir** [siberianLvolk/satisfying-buttons#2]
Currently, satisfying-buttons doesn't allow the option of changing the colour of the different buttons (such as `success` or `error`).

This can be done using something like:
```scss
$primary: #4e87ec;

.button.primary {
  // later...
  background-color: $primary;
}
```
